export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_MAIN_POSTS = 'ADD_MAIN_POSTS';
export const ADD_TOP_POSTS = 'ADD_TOP_POSTS';
export const ADD_RECOMEND_POSTS = 'ADD_RECOMEND_POSTS';
export const ADD_NOVELTY_POSTS = 'ADD_NOVELTY_POSTS';
export const ADD_STANDART_POSTS = 'ADD_STANDART_POSTS';